### PR TITLE
Add support for Travis builds (issue #20)

### PR DESCRIPTION
**Pull request by techtonik**
#20

Builds can be tracked here - https://travis-ci.org/techtonik/pyside2-setup - branch `travis`

[Build Status](https://travis-ci.org/techtonik/pyside2-setup)

### CODE REVIEW

**Comment by thopiekar** [comment]
Does Travis have also Qt5? Then I guess I have a fix for your failing builds I just found today.

**Comment by The-Compiler** [comment]
You can use `dist: trusty` to get a more recent Ubuntu (in a VM though, but that means you get root and can install anything via `sudo apt-get install`).

**Comment by thopiekar** [comment]
The problem is probably something else. Whenever you run qmake (there is no qmake-qt5) you'll need to run qmake as "qmake -qt5". qmake is actually a symlink to qtchooser which is a dynamic switch between different Qt installations, so when running qmake you'll need to append "-qt=5".
Will prepare a PR for this soon :wink:

**Comment by thopiekar** [comment]
Should be fixed with: https://github.com/PySide/pyside2-setup/commit/32938327b041c80acb057904ea72fd8582e6c4e1

**Comment by techtonik** [comment]
New build started - https://travis-ci.org/techtonik/pyside2-setup/builds/106577524

**Comment by thopiekar** [comment]
Hmm, I'm not familiar with Debian Sid. Can you take Ubuntu Wily or even Xenial and retry? Seems that Debian has its own packaging.
Maybe my implementation is of --qt=5 here is Ubuntu specific :disappointed:

**Comment by thopiekar** [comment]
(At least I remember that you choose Debian Sid as environment to build on. Can find it myself at the moment.)

**Comment by techtonik** [comment]
Debian Sid is not an environment - it is an additional apt-get source to install packages from. But it looks like installing Qt fetches some libs that conflict with system libraries for Ubuntu Precise, so this step never finishes.

**Comment by techtonik** [comment]
Found https://github.com/travis-ci/apt-source-whitelist/pull/238 - I guess I have to use `dist: trusty` for now as @The-Compiler suggested.

**Comment by thopiekar** [comment]
Ahh, I thought you can choose an environment where you want to run test builds, eg. Debian or Ubuntu and their releases. What is Travis using? Ubuntu? I see you importing a PPA?!

**Comment by techtonik** [comment]
Travis is using Ubuntu, but it doesn't work at the moment - build is stalled https://travis-ci.org/techtonik/pyside2-setup/jobs/106823612 and they don't know why https://www.traviscistatus.com/incidents/lpgbdfcmjhpk

I am importing PPA for Qt5, because they using Precise (12.04) which doesn't have this package.

**Comment by thopiekar** [comment]
To be honest in this case I wouldn't waste time and more on an own PPA then. I even set up a PPA but PySide is still broken at the moment. So I don't want to waste more time on this.
Getting pyside-setup working first is more important I think. At the beginning I didn't like to use it, but now I think it is very good to make quick tests.

**Comment by thopiekar** [comment]
Additionally Ubuntu Precise is very old....

**Comment by thopiekar** [comment]
Btw. we had the problem before that qmake didn't recognize "-qt=5". I added a platform-independent fix for it, because it also appears on Windows.
I don't know what you did in the mean time, so don't know whether you can revert some changes.

**Comment by ctismer** [comment]
not sure if I should test something or just merge the PR?

**Comment by thopiekar** [comment]
Would be great if we could get it working first. Additionally Travis does not seem to be optimal for Qt5, as far as I understood it here.

**Comment by techtonik** [comment]
I will rebase once there will be anything to merge.

**Comment by techtonik** [comment]
Qt5 is there, but compilation fails https://travis-ci.org/techtonik/pyside2-setup/jobs/107316415

**Comment by thopiekar** [comment]
Yes, but it is only 5.2.1

**Comment by thopiekar** [comment]
Finding a PPA with Qt >= 5.4 for Precise will be very hard.

**Comment by techtonik** [comment]
@thopiekar https://launchpad.net/~beineri/+archive/ubuntu/opt-qt551 but why 5.5 is needed?

**Comment by thopiekar** [comment]
The Qt API changes with every version. To get PySide2 working we decided to choose a minimum version and work on that.

Btw. I took a closer look on the PPA. The packager of the PPA made his own package-naming..
Try to enable the PPA again and install the "qt55-meta-full" package.

**Comment by techtonik** [comment]
Can not find Qt5 installation - https://travis-ci.org/techtonik/pyside2-setup/jobs/107385453

**Comment by thopiekar** [comment]
Run as command "qtchooser -l" before "python setup.py *". Just to
understand which qt5 installations are known by qtchooser.

**Comment by thopiekar** [comment]
Ah, that's great! Now add "--qt=opt-qt55" to "python setup.py".

**Comment by thopiekar** [comment]
Our meta-package only installs the libraries not the -dev packages as we can see in https://travis-ci.org/techtonik/pyside2-setup/jobs/107415487#L278
I'm looking now whether there is a meta-package to install all -dev packages...

**Comment by thopiekar** [comment]
Or are all of these qt55* packages also including the headers and cmake modules?

I don't think you'll need to update cmake because

```
$ apt-file find Qt5Config.cmake
libaccounts-qt5-dev: /usr/lib/x86_64-linux-gnu/cmake/AccountsQt5/AccountsQt5Config.cmake
libphonon4qt5-dev: /usr/lib/x86_64-linux-gnu/cmake/phonon4qt5/Phonon4Qt5Config.cmake
libsignon-qt5-dev: /usr/lib/x86_64-linux-gnu/cmake/SignOnQt5/SignOnQt5Config.cmake
libtelepathy-qt5-dev: /usr/lib/x86_64-linux-gnu/cmake/TelepathyQt5/TelepathyQt5Config.cmake
qtbase5-dev: /usr/lib/x86_64-linux-gnu/cmake/Qt5/Qt5Config.cmake
qtbase5-gles-dev: /usr/lib/x86_64-linux-gnu/cmake/Qt5/Qt5Config.cmake
```

this Qt5Config is part of the qtbase5-dev package.

**Comment by thopiekar** [comment]
Here it is:

**Comment by techtonik** [comment]
@thopiekar but `qt55base` is installed.

**Comment by thopiekar** [comment]
Yes, the problem is that "/opt/qt55/lib/cmake/Qt5/" is a non-default path for cmake modules.
What we'll need is a clean solution to set the CMAKE_MODULE_PATH environment variable.

**Comment by thopiekar** [comment]
It should be something like: ```CMAKE_MODULE_PATH="/opt/qt55/lib/cmake/Qt5/;/usr/share/cmake-2.8/Modules/"```
Add it before the ```python setup.py```

**Comment by thopiekar** [comment]
Ok, we need to set more paths.
```CMAKE_MODULE_PATH="/opt/qt55/lib/cmake/Qt5/;/opt/qt55/lib/cmake/Qt5Concurrent/;/opt/qt55/lib/cmake/Qt5Core/;/opt/qt55/lib/cmake/Qt5DBus/;/opt/qt55/lib/cmake/Qt5Gui/;/opt/qt55/lib/cmake/Qt5Network/;/opt/qt55/lib/cmake/Qt5OpenGL/;/opt/qt55/lib/cmake/Qt5OpenGLExtensions/;/opt/qt55/lib/cmake/Qt5PrintSupport/;/opt/qt55/lib/cmake/Qt5Sql/;/opt/qt55/lib/cmake/Qt5Test/;/opt/qt55/lib/cmake/Qt5Widgets/;/opt/qt55/lib/cmake/Qt5Xml/;/usr/share/cmake-2.8/Modules/```

**Comment by techtonik** [comment]
[Build Status](https://travis-ci.org/techtonik/pyside2-setup)

**Comment by thopiekar** [comment]
I see it building :smile:

**Comment by thopiekar** [comment]
Is it allowed in Travis to build in parallel?

**Comment by techtonik** [comment]
Yes, why not? Build are not dependent on each other.

**Comment by thopiekar** [comment]
I don't mean that. I thought more about using "python* setup.py --jobs=[int]" :wink:

**Comment by thopiekar** [comment]
Yeah, it worked :grin:

**Comment by thopiekar** [comment]
Ok, only saved ~5min if I'm not wrong. I think we can build using one job (same as removing the option again). Looks like the Travis environment is under load all the time, so we don't win much time.

**Comment by thopiekar** [comment]
Ah, and also add "--build-tests".

**Comment by thopiekar** [comment]
Additionally: I read the currently running logs. You don't need ```qtchooser -l```, also ```--qt=opt-qt55``` isn't needed anymore if you use this ```*env.sh```.

**Comment by techtonik** [comment]
Test are not building - https://github.com/PySide/shiboken2/issues/21

**Comment by techtonik** [comment]
Rebased and cleaned this PR in #31.

**Pull request closed without merging**
