### PR TITLE
Travis2

### PR DESCRIPTION
**Pull request by techtonik**
This is a revised PR from #26.

Closes issue #20.

Builds are be tracked here - https://travis-ci.org/techtonik/pyside2-setup - branch `travis2`

[Build Status](https://travis-ci.org/techtonik/pyside2-setup)

### CODE REVIEW

**Comment by thopiekar** [comment]
Thanks! I like it, but I in my point of view @ctismer has the last word to merge this or not :wink:

**Comment by techtonik** [comment]
@ctismer it is ready to merge! =)

**Comment by techtonik** [comment]
:+1:  =)

**Comment by thopiekar** [comment]
By the way I just added the missing label about the build status to the
README.md :wink:

**Comment by techtonik** [comment]
@thopiekar I just edited #25 to make it a table on top. Can you also open an AppVeyor team account in #24 so that all links to build become official?

**Comment by thopiekar** [comment]
Don't know. I don't have full permission on PySide but I can try it later.

Thank you again for the PR btw.

**Comment by ctismer** [comment]
Thomas, I'd be happy to grant you
full access. But you need to ask me. 
Some people dislike super powers :-)

Sent from my Ei4Steve

**Comment by thopiekar** [comment]
That's not a problem :wink:

**Pull request merged**
