### PR TITLE
# Port piechart.py

### PR DESCRIPTION
**Pull request by puskini33**

### CODE REVIEW

**Comment by cmaureir** [comment]
Thanks for your contribution. PySide2 development happens in Gerrit, so it would be really good if you can submit your example there: https://wiki.qt.io/Qt_for_Python/Development_Getting_Started

Otherwise, if you grant me permission, I can submit the example on your behalf.

**Comment by puskini33** [comment]
Thank you! Sure, I grant you permission to submit my example on my behalf.

**Comment by cmaureir** [comment]
Thanks @puskini33 the examples got merged and were officially released: https://codereview.qt-project.org/c/pyside/pyside-setup/+/300582

**Comment by puskini33** [comment]
Cool @cmaureir ! Thank you!

**Pull request closed without merging**
