### PR TITLE
.rst to md for unified doc types.

### PR DESCRIPTION
**Pull request by IronManMark20**
I updated things. Maybe I will add more build instructions.

### CODE REVIEW

**Comment by ctismer** [comment]
Why do you want to throw the old readme.rst completely away? I don't thing the author (Roman) would be so happy.

**Comment by IronManMark20** [comment]
Mostly because all of the links are for PySide1. (Readthedocs, issues,etc), and the rest is either not applicable, or already elsewhere. I might re-integrate the bit about what PySide is (I like it actually), so not _everything_ is going away, just the stuff that might confuse people.

**Comment by IronManMark20** [comment]
I put his blurb back in as it is still relevant, but the rest is all about Qt4.8 and PySide, so I thought it would only confuse.

**Comment by ctismer** [comment]
Thanks a lot!

**Pull request merged**
